# Support me

[crypto wallet reflink -19% fee](https://web3.okx.com/join/MASELKO955)

[OKX bloker ref link](https://my.okx.com/join/37179746)

[My Usdc wallet](https://steamcommunity.com/sharedfiles/filedetails/?id=3611051169)

[MY bat wallet](https://steamcommunity.com/sharedfiles/filedetails/?id=3611053516)
